=begin
#madana-api

#<h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>

The version of the OpenAPI document: 0.4.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AccountServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountServiceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AccountServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountServiceApi' do
    it 'should create an instance of AccountServiceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AccountServiceApi)
    end
  end

  # unit tests for activate_user
  # @param token 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'activate_user test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for create_object
  # Sends an Password reset mail to the given MailAddress.
  # Sends an Password reset mail to the given MailAddress
  # @param [Hash] opts the optional parameters
  # @option opts [JsonMDNMailAddress] :body - the MaiAddress under which the user has signed up
  # @return [File]
  describe 'create_object test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for request_verification_mail
  # Used to request a new  activation-mail for the user.
  # Used to request a new  activation-mail for the user
  # @param [Hash] opts the optional parameters
  # @return [Hash<String, Object>]
  describe 'request_verification_mail test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_object
  # Receives the Password reset and tries to set the provided password for the user.
  # Receives the Password reset and tries to set the provided password for the user. The Password will only be set if a valid token is provided
  # @param [Hash] opts the optional parameters
  # @option opts [JsonMDNPasswordReset] :body - the MDN_PasswordReset Object
  # @return [File]
  describe 'update_object test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
