=begin
#madana-api

#<h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>

The version of the OpenAPI document: 0.4.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::SocialServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SocialServiceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::SocialServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SocialServiceApi' do
    it 'should create an instance of SocialServiceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::SocialServiceApi)
    end
  end

  # unit tests for get_my_profile
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_my_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_platforms2
  # Returns all Platforms / Systems that can be Connected to the MADANA Service.
  # Returns all Platforms / Systems that can be Connected to the MADANA Service
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_platforms2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_ranking
  # Returns the Ranking by PTS within the System.
  # Returns the Ranking by PTS within the System
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_ranking test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_social_platform_feed
  # @param platform 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_social_platform_feed test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_profile
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :simple 
  # @return [File]
  describe 'get_user_profile test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_user_profile_0
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_user_profile_0 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
