=begin
#madana-api

#<h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>

The version of the OpenAPI document: 0.4.12

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for   MadanaSampleclientRuby::UserServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UserServiceApi' do
  before do
    # run before each test
    @api_instance =   MadanaSampleclientRuby::UserServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UserServiceApi' do
    it 'should create an instance of UserServiceApi' do
      expect(@api_instance).to be_instance_of(  MadanaSampleclientRuby::UserServiceApi)
    end
  end

  # unit tests for create_object2
  # Creates a new user object.
  # Creates a new user object
  # @param [Hash] opts the optional parameters
  # @option opts [String] :referrer 
  # @option opts [JsonMDNUser] :body provided user object inheriting properties and credentials
  # @return [File]
  describe 'create_object2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_object
  # Deletes an User based on the provided id and securitycontext.
  # Deletes an User based on the provided id and securitycontext
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'delete_object test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_object_0
  # Deletes linked account from the user and securitycontext.
  # Deletes linked account from the user and securitycontext
  # @param ident 
  # @param platform 
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'delete_object_0 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_avatars
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_avatars test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_certificates
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_certificates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_object2
  # @param username 
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'get_object2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_avatar
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [JsonMDNUserProfileImage] :body 
  # @return [File]
  describe 'set_avatar test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for set_settings
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [JsonMDNUserSetting] :body 
  # @return [File]
  describe 'set_settings test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_object2
  # Updates Userproperties based on the provided user object.
  # Updates Userproperties based on the provided user object
  # @param username 
  # @param [Hash] opts the optional parameters
  # @option opts [JsonMDNUser] :body the new user object inherting all properties that should be change
  # @return [File]
  describe 'update_object2 test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
