=begin
#madana-api

#<h1>Using the madana-api</h1>        <p>This documentation contains a Quickstart Guide, relating client functionality and information about the available         endpoints and used datamodels.   </p>       <p> The madana-api and its implementations are still in heavy development. This means that there may be problems in our protocols, or there may be mistakes in our implementations. We take security vulnerabilities very seriously. If you discover a security issue, please bring it to our attention right away! If you find a vulnerability that may affect live deployments -- for example, by exposing a remote execution exploit -- please send your report privately to info@madana.io. Please DO NOT file a public issue. If the issue is a protocol weakness that cannot be immediately exploited or something not yet deployed, just discuss it openly   </p>   <br>   <p> Note: Not all functionality might be acessible without having accquired and api-license token. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a> </p>       <br>

The version of the OpenAPI document: 0.4.14-master.16

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.0

=end

# Common files
require 'madana-sampleclient-ruby/api_client'
require 'madana-sampleclient-ruby/api_error'
require 'madana-sampleclient-ruby/version'
require 'madana-sampleclient-ruby/configuration'

# Models
require 'madana-sampleclient-ruby/models/json_disk_config'
require 'madana-sampleclient-ruby/models/json_enclave_process'
require 'madana-sampleclient-ruby/models/json_enclave_run_request'
require 'madana-sampleclient-ruby/models/json_enclave_running_attestation'
require 'madana-sampleclient-ruby/models/json_enclave_running_attestation_approval'
require 'madana-sampleclient-ruby/models/json_enclave_running_attestation_approval_all_of'
require 'madana-sampleclient-ruby/models/json_environment'
require 'madana-sampleclient-ruby/models/json_environment_publishing_request'
require 'madana-sampleclient-ruby/models/json_ipfs_system_info'
require 'madana-sampleclient-ruby/models/json_mdna_user_object'
require 'madana-sampleclient-ruby/models/json_mdn_certificate'
require 'madana-sampleclient-ruby/models/json_mdn_data'
require 'madana-sampleclient-ruby/models/json_mdn_mail_address'
require 'madana-sampleclient-ruby/models/json_mdno_auth_token'
require 'madana-sampleclient-ruby/models/json_mdn_password_reset'
require 'madana-sampleclient-ruby/models/json_mdn_setting'
require 'madana-sampleclient-ruby/models/json_mdn_social_user_object'
require 'madana-sampleclient-ruby/models/json_mdn_token'
require 'madana-sampleclient-ruby/models/json_mdn_user'
require 'madana-sampleclient-ruby/models/json_mdn_user_all_of'
require 'madana-sampleclient-ruby/models/json_mdn_user_credentials'
require 'madana-sampleclient-ruby/models/json_mdn_user_profile_image'
require 'madana-sampleclient-ruby/models/json_mdn_user_setting'
require 'madana-sampleclient-ruby/models/json_mdn_user_setting_all_of'
require 'madana-sampleclient-ruby/models/json_network_interface'
require 'madana-sampleclient-ruby/models/json_node_info'
require 'madana-sampleclient-ruby/models/json_process'
require 'madana-sampleclient-ruby/models/json_run_config'
require 'madana-sampleclient-ruby/models/json_signed_data'
require 'madana-sampleclient-ruby/models/json_wireguard_interface'
require 'madana-sampleclient-ruby/models/json_wireguard_interface_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_disk_config'
require 'madana-sampleclient-ruby/models/xml_ns0_disk_config_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_process'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_process_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_running_attestation'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_running_attestation_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_running_attestation_approval'
require 'madana-sampleclient-ruby/models/xml_ns0_enclave_running_attestation_approval_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_environment'
require 'madana-sampleclient-ruby/models/xml_ns0_environment_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_ipfs_system_info'
require 'madana-sampleclient-ruby/models/xml_ns0_ipfs_system_info_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_setting'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_setting_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_user_profile_image'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_user_profile_image_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_user_setting'
require 'madana-sampleclient-ruby/models/xml_ns0_mdn_user_setting_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_network_interface'
require 'madana-sampleclient-ruby/models/xml_ns0_network_interface_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_node_info'
require 'madana-sampleclient-ruby/models/xml_ns0_node_info_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_process'
require 'madana-sampleclient-ruby/models/xml_ns0_run_config'
require 'madana-sampleclient-ruby/models/xml_ns0_run_config_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_signed_data'
require 'madana-sampleclient-ruby/models/xml_ns0_signed_data_all_of'
require 'madana-sampleclient-ruby/models/xml_ns0_wireguard_interface'
require 'madana-sampleclient-ruby/models/xml_ns0_wireguard_interface_all_of'

# APIs
require 'madana-sampleclient-ruby/api/account_service_api'
require 'madana-sampleclient-ruby/api/authentication_service_api'
require 'madana-sampleclient-ruby/api/certificate_service_api'
require 'madana-sampleclient-ruby/api/data_collection_service_api'
require 'madana-sampleclient-ruby/api/enclave_service_api'
require 'madana-sampleclient-ruby/api/environment_service_api'
require 'madana-sampleclient-ruby/api/node_service_api'
require 'madana-sampleclient-ruby/api/organization_service_api'
require 'madana-sampleclient-ruby/api/request_service_api'
require 'madana-sampleclient-ruby/api/social_platform_service_api'
require 'madana-sampleclient-ruby/api/social_service_api'
require 'madana-sampleclient-ruby/api/system_service_api'
require 'madana-sampleclient-ruby/api/user_service_api'

module   MadanaSampleclientRuby
  class << self
    # Customize default settings for the SDK using block.
    #     MadanaSampleclientRuby.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
